default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: readinglist_development

test:
  <<: *default
  database: readinglist_test

production:
  <<: *default
  database: readinglist_production